name: OpenWRT Build

on:
  push:
    branches:
      - main # 替换为你想要触发构建的分支

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
        rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
    
    - name: Clone OpenWRT source code
      run: git clone -b openwrt-23.05 https://github.com/openwrt/openwrt.git

    - name: Copy configuration file
      run: cp config_default/.config openwrt/

    - name: Update and install feeds
      run: |
        cd openwrt/
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download and compile OpenWRT
      run: |
        cd openwrt/
        make download -j$(nproc)
        make V=s -j$(nproc)

    - name: Upload artifacts (可选)
      uses: actions/upload-artifact@v3
      with:
        name: openwrt-build
        path: openwrt/bin/targets/ # 替换为编译后固件所在的目录